### PR TITLE
fix for cast error

### PR DESCRIPTION
**Pull request by yohto**
### What is the necessity of this update? What is updated?
Add data type check and cast the data

### How did you do the test? (Not required for updating documents)
Verify with data that the error occurred

### CODE REVIEW

**Comment by yohto** [comment]
@koijima 
I think it is better to fix other Hive version branches.
Can I fix them?

**Comment by koijima** [comment]
Bug fixes look good.
I do not know how this function is called, so let's investigate in the future.

**Comment by yohto** [comment]
I fixed other Hive version branches and create PR each.
Please check them.

**Comment by yohto** [comment]
Thank you, I will investigate this method's feature later.

**Pull request merged**
