### PR TITLE
[Yosegi-36]The Timestamp interface is different in Hive 3.X.

### PR DESCRIPTION
**Pull request by koijima**
### What is the necessity of this update? What is updated?
Fixed the code because Date interface is different in 3.X.

### CODE REVIEW

**Comment by yohto** [comment]
On your local branch, mvn test does not pass.

**Comment by yohto** [comment]
[ERROR] Errors:
[ERROR]   TestHiveTimestampPrimitiveConverter.T_1:46 » ClassCast org.apache.hadoop.hive....
[INFO]
[ERROR] Tests run: 139, Failures: 0, Errors: 1, Skipped: 0

**Comment by yohto** [comment]
LGTM

**Comment by koijima** [comment]
Thank you for the review!

**Pull request merged**
